chore(deps): update exp module
CircleCI-Public/circle-policy-agent pull request #120
Opened 2023-12-08 09:52 UTC by loderunner

## Rationale

The `slices` package in the `golang.org/x/exp` has changed the signature of comparison functions from [returning a `bool`](https://pkg.go.dev/golang.org/x/exp@v0.0.0-20230713183714-613f0c0eb8a1/slices#SortFunc) to [returning an `int`](https://pkg.go.dev/golang.org/x/exp@v0.0.0-20230728194245-b0cb94b80691/slices#SortFunc).

This breaking change impacts Go programs relying on `circle-policy-agent` with a more recent version of the `exp` module, and prevents them from building.

```
circle-policy-agent@v0.0.702/cpa/tester/runner.go:164:30: type func(a NamedTest, b NamedTest) bool of func(a, b NamedTest) bool {…} does not match inferred type func(a NamedTest, b NamedTest) int for func(a E, b E) int
```

This PR updates the `exp` package and fixes the usage of `slices.SortFunc` to reflect the new signature.

## Changes

* Update the `golang.org/x/exp` module to `v0.0.0-20231206192017-f3f8817b8deb`
* Fix usage of `slices.SortFunc` to reflect breaking changes in the `golang.org/x/exp` module

2023-12-08 15:54 UTC, jbialy approved these changes
lgtm!

2023-12-08 16:01 UTC, gosuku requested changes
Think this also requires changes to https://github.com/CircleCI-Public/circle-policy-agent/blob/main/cpa/parsing.go#L131

2023-12-08 16:12 UTC, loderunner commented
I don't see where this should change. As far as I understand, the function passed as argument to`IndexFunc`  has not changed signature, and [still returns a `bool`.](https://pkg.go.dev/golang.org/x/exp@v0.0.0-20230728194245-b0cb94b80691/slices#IndexFunc) Am I missing something? 🤔

2023-12-08 16:16 UTC, gosuku commented
Yes, actually that was my misread of the return type of `IndexFunc` as the return type of the func parameter.

2023-12-08 16:16 UTC, gosuku approved these changes
LGTM

2024-12-10 17:11 UTC, vallieres commented
Closing, as this change was rolled in another pull request. We don't require the x/exp dependency anymore.

2024-12-10 17:11 UTC, closed without merging